# Generated by Django 5.1.4 on 2025-01-14 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='Категория рекламы')),
            ],
            options={
                'verbose_name': 'Категорию рекламы',
                'verbose_name_plural': 'Категории рекламы',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Фирма-производитель')),
            ],
            options={
                'verbose_name': 'Фирма-производитель',
                'verbose_name_plural': 'Фирмы-производители',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ManufacturerCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Страна-изготовитель')),
            ],
            options={
                'verbose_name': 'Странa-изготовитель',
                'verbose_name_plural': 'Страны-изготовители',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Adv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='adv/%Y/%m/%d', verbose_name='Рекламный баннер')),
                ('adv_type', models.ForeignKey(default='no_category', on_delete=django.db.models.deletion.SET_DEFAULT, to='shop_site.advtype', verbose_name='Категория рекламы')),
            ],
            options={
                'verbose_name': 'Рекламное объявление',
                'verbose_name_plural': 'Рекламные объявления',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Слаг')),
                ('name', models.CharField(max_length=100, verbose_name='Товар')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('stock_balance', models.IntegerField(default=0, verbose_name='Количество')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_site.category', verbose_name='Категория')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shop_site.manufacturercountry', verbose_name='Страна-изготовитель')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_site.manufacturer', verbose_name='Фирма-производитель')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PriceChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_price_change', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения цены')),
                ('old_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Старая цена')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Текущая цена')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_site.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Историю изменения цены',
                'verbose_name_plural': 'Истории изменения цен',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='products/photo/%Y/%m/%d', verbose_name='Фотография')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_site.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
    ]
