# Generated by Django 5.1.4 on 2025-01-12 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='Категория рекламы')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='ManufacturerCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Страна-изготовитель')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название филиала')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес филиала')),
            ],
        ),
        migrations.CreateModel(
            name='Adv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='adv/%Y/%m/%d', verbose_name='Рекламный баннер')),
                ('adv_type', models.ForeignKey(default='no_category', on_delete=django.db.models.deletion.SET_DEFAULT, to='shop_site.advtype', verbose_name='Категория рекламы')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Фирма-производитель')),
                ('country', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shop_site.manufacturercountry', verbose_name='Страна-изготовитель')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Слаг')),
                ('title', models.CharField(max_length=100, verbose_name='Товар')),
                ('stock_balance', models.IntegerField(default=0, verbose_name='Количество')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_site.category', verbose_name='Категория')),
                ('manufacturer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shop_site.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='PriceChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_price_change', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения цены')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Старая цена')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Текущая цена')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_site.product', verbose_name='Товар')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='products/photo/%Y/%m/%d', verbose_name='Фотография')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_site.product', verbose_name='Товар')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('product', models.ForeignKey(default='product does not exist', on_delete=django.db.models.deletion.SET_DEFAULT, to='shop_site.product', verbose_name='Товар')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='Количество')),
                ('product', models.ForeignKey(default='product has been deleted', on_delete=django.db.models.deletion.SET_DEFAULT, to='shop_site.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
                'ordering': ('product',),
            },
        ),
        migrations.CreateModel(
            name='Delivries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='Количество')),
                ('delivery_date', models.DateField(auto_now_add=True, verbose_name='Дата поставки')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_site.product', verbose_name='Товар')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_site.store', verbose_name='Филиал')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата оплаты')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_site.cart', verbose_name='Корзина')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop_site.store', verbose_name='Филиал')),
            ],
            options={
                'verbose_name': 'Счет',
                'verbose_name_plural': 'Счета',
                'ordering': ('purchase_date',),
            },
        ),
    ]
