# Generated by Django 5.1.4 on 2025-01-13 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_site', '0002_alter_adv_options_alter_advtype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_site.manufacturer', verbose_name='Фирма-производитель'),
        ),
    ]
