# Generated by Django 5.1.4 on 2025-01-15 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_site', '0006_alter_product_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(blank=True, default=0,
                                    on_delete=django.db.models.deletion.SET_DEFAULT, to='shop_site.manufacturer', verbose_name='Фирма-производитель'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='shop_site.subcategory', verbose_name='Подкатегория'),
        ),
    ]
