# Generated by Django 5.1.4 on 2025-01-15 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_site', '0008_alter_product_manufacturer_alter_product_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricechange',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='shop_site.product', verbose_name='Товар'),
        ),
    ]
