# Generated by Django 5.1.4 on 2025-01-17 13:03

import apps.shop_site.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_site', '0010_alter_pricechange_options_product_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default='products/photo/flag_rf.jpg', upload_to=apps.shop_site.models.Photo.set_img_filename, verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='pricechange',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Текущая цена'),
        ),
    ]
