# Generated by Django 5.1.4 on 2025-01-20 16:47

import apps.shop_site.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_site', '0011_alter_photo_photo_alter_pricechange_current_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default='products/photo/korobka.jpg', upload_to=apps.shop_site.models.Photo.set_img_filename, verbose_name='Фотография'),
        ),
    ]
