# Generated by Django 5.1.4 on 2025-02-01 15:21

import apps.shop_site.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_site', '0012_alter_photo_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-id',), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default='products/photo/korobka.png', upload_to=apps.shop_site.models.Photo.set_img_filename, verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='pricechange',
            name='current_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Текущая цена'),
        ),
        migrations.AlterField(
            model_name='pricechange',
            name='old_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Старая цена'),
        ),
    ]
