# Generated by Django 5.1.6 on 2025-02-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_site', '0013_alter_product_options_alter_photo_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='params',
            field=models.CharField(default=0, max_length=200, verbose_name='Товар'),
            preserve_default=False,
        ),
    ]
