# Generated by Django 5.1.4 on 2025-01-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='users/avatars/default_avatar.png', upload_to='users/avatars/%Y/%m/%d', verbose_name='Аватар'),
        ),
    ]
